### ISSUE TITLE
this still works?

### ISSUE THREAD

**Issue by gabrielmancini** [pouchdb/pouchdb-list#29]
witch version of pouch work this?
i got an error:

```
Uncaught (in promise) TypeError: db.getUrl is not a function
```

**Comment by marten-de-vries** [comment]
Thanks for reporting. It's indeed broken. Closing in favour of https://github.com/pouchdb/pouchdb-req-http-query/issues/18 , because that one is filed against the package which actually uses the deprecated functionality.

**Comment by gabrielmancini** [comment]
Thanks for the answer @marten-de-vries.
why deprecated? Map Reduce List and Show functions will be remove from core of couchdb?

**Comment by marten-de-vries** [comment]
@gabrielmancini You misunderstood me. As far as I know, those features are not going to be removed from CouchDB, even if there is not much focus on 'the CouchApp way of doing things' lately.

pouchdb-req-http-query uses ``db.getUrl()``, which was an undocumented PouchDB API that was removed ('deprecated') somewhat recently. This module (pouchdb-list) depends upon it. Hope this helps.
